version: '3.7'
services:
  mysqldb:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - msql-vol:/var/lib/mysql
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.7-management"
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672

volumes:
  msql-vol:
